version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2.0.15-openssl
    container_name: mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./passwd:/mosquitto/config/passwd
      - ./aclfile.acl:/mosquitto/config/aclfile.acl
    ports:
      - 1883:1883
      - 9001:9001
